name: Daily Telegram Bot

on:
  schedule:
    # Runs every weekday (Monday-Friday) at 19:00 UTC
    # Adjust timezone as needed - GitHub Actions uses UTC
    - cron: '0 19 * * 1-5'
  workflow_dispatch: # Allow manual trigger for testing

jobs:
  send-daily-content:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run bot
      env:
        PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python bot/main.py

